#' Plot the distribution of sRNA lengths/classes
#'
#' @description \code{RNAdistribution} plots the distribution of dicer-derived
#' sRNA classes across samples or across the sRNA consensus
#' determined by the function [mobileRNA::RNAdicercall()].
#'
#' @param data data.frame; generated by [mobileRNA::RNAimport()], can also plot 
#' information generated by [mobileRNA::RNAdicercall()].
#'
#' @param samples character; stores names of samples to analyse and plot.
#' Argument is required for plotting individual sample replicates, either
#' individually, overlapped together or in a facet. Use the sample
#' replicate names present in the data frame, select samples you wish
#' to plot. Is not required when plotting the sRNA consensus using the argument
#' \code{total=TRUE}.
#'
#' @param facet logical; forms a matrix of panels defined by row and column
#' faceting variables. It plots the results for each sample as a bar-chart
#' and contains it within a single plot. The number of rows in the facet can
#' be changed using the argument \code{facet.arrange}.
#' Default \code{facet = TRUE} , plots each sample separately when
#' \code{facet = FALSE} .
#'
#' @param facet.arrange numeric; value supplied to define the number of columns
#' to include in the facet. This argument is piped into the ` ncol`  argument in
#' [ggplot2::facet_wrap()] to define the number of columns. By default, this is
#' set to 3.
#'
#' @param colour character; Default colour is "black".
#'
#' @param style character; \code{style="line"}, \code{style="bar"} or 
#' \code{style="consensus"}. Instructs how to plot the data. Where 
#' \code{style="line"} plots a line graph. Where \code{style="bar"} plots a bar 
#' graph. Where \code{style="consensus"} produces the line graph for the 
#' sRNA dicer-derived consensus generated by the function 
#' [mobileRNA::RNAdicercall()].
#'
#' @param together logical; generates a single line graph, containing all 
#' sample replicate information. Default \code{together=TRUE}.
#'
#'@param relative logical; used in conjunction with  \code{style="consensus"}. 
#'Instructs plotting of the relative frequency of all sRNA classes across the 
#'data defined by the consensus dicer-derived sRNA column (see 
#'[mobileRNA::RNAdicercall()] function for more information). 
#'
#'
#'@details
#'
#'The function can be used to plot a variety of different comparisons and plots.
#'It can be used to plot the distribution of sRNA classes within each sample
#'replicate, which can be represented as a bar chart \code{style="bar"} or a
#'line graph \code{style="line"}. These plots can be represented individually or
#'in a single plot facet \code{facet="TRUE"} by default. While the option 
#' \code{style="consensus"}, plots the distribution of the consensus 
#' dicer-derived sRNA classes determined by the [RNAdicercall()] function
#'
#'
#'To plot the sRNA dicer-derived clusters identified in each sample, the
#'function extracts the information from the sRNA data set and calculates the
#'total number of each RNA class identified within a sample, for all samples.
#'
#'Alternatively, the function allows you to plot the line graph for each sample
#'together, overlapped on a single graph \code{together=TRUE}. This is not an
#'option for bar plots.
#'
#'@return The function returns a list containing the results in the form of a
#'data frame and the plot(s). To access an element, simply use the "$" symbol,
#'and the elements "data" and "plot" will appear. The `samples` argument allows
#'uses to plot specific samples in a single plot (facet bar plot or line graph).
#'This can encourage closer comparison between sample replicates.
#'
#' @examples
#' # load data 
#' data('sRNA_data')
#'
#' p1 <- RNAdistribution(data = sRNA_data, style = "line")
#'
#' p2 <- RNAdistribution(data = sRNA_data, style = "line", together = FALSE)
#'
#' p3 <- RNAdistribution(data = sRNA_data, style = "bar")
#'
#' p3.2 <- RNAdistribution(data = sRNA_data, style = "bar",
#'                        samples = c("heterograft_1", "heterograft_2",
#'                        "heterograft_3"))
#'
#' p4 <- RNAdistribution(data = sRNA_data, style = "bar", facet = FALSE)
#'
#' p5 <- RNAdistribution(data = sRNA_data, style = "bar",
#'                       facet = TRUE, facet.arrange = 2 )
#'
#'
#' # Run function to define sRNA class for each cluster.
#' sRNA_data_dicercall <- RNAdicercall(data = sRNA_data, tidy=TRUE)
#'
#'p6 <- RNAdistribution(data = sRNA_data_dicercall, style = "consensus")
#'
#' @export
#' @importFrom BiocGenerics grep
#' @importFrom dplyr %>%
#' @importFrom dplyr select
#' @importFrom dplyr count
#' @importFrom dplyr mutate
#' @importFrom tidyselect all_of
#' @importFrom data.table setDT
#' @importFrom ggplot2 ggplot
#' @importFrom ggplot2 aes_string
#' @importFrom ggplot2 geom_bar
#' @importFrom ggplot2 labs
#' @importFrom ggplot2 aes
#' @importFrom ggplot2 guides
#' @importFrom ggplot2 guide_legend
#' @importFrom ggplot2 unit
#' @importFrom ggplot2 element_text
#' @importFrom ggplot2 element_blank
#' @importFrom ggplot2 element_line
#' @importFrom ggplot2 element_rect
#' @importFrom ggplot2 margin
#' @importFrom tidyr gather
#' @importFrom data.table melt
#' @importFrom ggplot2 facet_wrap
#' @importFrom ggplot2 theme_classic
#' @importFrom ggplot2 geom_point
#' @importFrom ggplot2 geom_line
#' @importFrom ggplot2 xlab
#' @importFrom ggplot2 ylab
#' @importFrom ggplot2 labs
#'
RNAdistribution  <- function (data, samples = NULL, style, 
                              facet = TRUE, facet.arrange = 3, colour = "black", 
                              together = TRUE, relative = FALSE) {
  if (base::missing(data) || !base::inherits(data, c("data.frame"))) {
    stop("data must be a data frame, see ?help for more details")
  }
  if (missing(style) || !is.character(style)) {
    stop("style parameter is missing or not a character vector.")
  }
  
  # Check if style is one of the allowed values
  allowed_styles <- c("line", "bar", "consensus")
  if (!style %in% allowed_styles) {
    stop("style parameter must be one of 'line', 'bar', or 'consensus'.")
  }
  
  if (style == "consensus") {
    x <- data %>% dplyr::count(DicerConsensus)
    if (!relative == FALSE) {
      x <- x %>% dplyr::mutate(freq = n/sum(n))
      p1 <- ggplot2::ggplot(x, ggplot2::aes(x = DicerConsensus, 
                                            y = freq, group = 1)) + 
        ggplot2::geom_point() + 
        ggplot2::geom_line() + ggplot2::theme_classic() + 
        ggplot2::xlab("sRNA Class") + 
        ggplot2::ylab("Relative frequency")+
        ggplot2::scale_y_continuous(expand = c(0, 0), limits = c(0, 1))  +
        ggplot2::theme_bw()+
        ggplot2::theme(legend.position = "none",
              legend.text = ggplot2::element_text(size= 12, margin = ggplot2::margin(5,5,5,5)),
              legend.title = ggplot2::element_text(size = 14, face = "bold"),
              axis.text.x = ggplot2::element_text(colour = "black", size = 14, face = "bold", margin = ggplot2::margin(t = 10, b = 4)),
              axis.text.y = ggplot2::element_text(colour = "black", size = 14,  face = "bold", margin = ggplot2::margin(r = 10)),
              panel.grid.major = ggplot2::element_blank(), panel.grid.minor = ggplot2::element_blank(),
              panel.background = ggplot2::element_blank(), axis.line = ggplot2::element_line(colour = "black"),
              panel.border = ggplot2::element_rect(color = "white", size = 1),
              axis.title.y = ggplot2::element_text(margin = ggplot2::margin(r = 15), size = 18, face = "bold"),
              axis.title.x = ggplot2::element_text(margin = ggplot2::margin(t = 15), size = 18, face = "bold"),
              plot.margin = ggplot2::unit(c(0.1, 0.1,0.1, 0.1),"inches") )
    }
    else 
      p1 <- ggplot2::ggplot(x, ggplot2::aes(x = DicerConsensus, 
                                            y = n, group = 1)) + 
        ggplot2::geom_point() + ggplot2::geom_line() + 
        ggplot2::theme_classic() + ggplot2::xlab("sRNA Class") + 
        ggplot2::ylab("Count")+
        ggplot2::theme_bw()+
        ggplot2::theme(legend.position = "none",
               legend.text = ggplot2::element_text(size= 12, margin = ggplot2::margin(5,5,5,5)),
               legend.title = ggplot2::element_text(size = 14, face = "bold"),
               axis.text.x = ggplot2::element_text(colour = "black", size = 14, face = "bold", margin = ggplot2::margin(t = 10, b = 4)),
               axis.text.y = ggplot2::element_text(colour = "black", size = 14,  face = "bold", margin = ggplot2::margin(r = 10)),
               panel.grid.major = ggplot2::element_blank(), panel.grid.minor = ggplot2::element_blank(),
               panel.background = ggplot2::element_blank(), axis.line = ggplot2::element_line(colour = "black"),
               panel.border = ggplot2::element_rect(color = "white", size = 1),
               axis.title.y = ggplot2::element_text(margin = ggplot2::margin(r = 15), size = 18, face = "bold"),
               axis.title.x = ggplot2::element_text(margin = ggplot2::margin(t = 15), size = 18, face = "bold"),
               plot.margin = ggplot2::unit(c(0.1, 0.1,0.1, 0.1),"inches") )
    out <- list(plot = p1, data = x)
    return(out)
    print(x)
    print(p1)
  }
  else {
    if (base::missing(style) || !style %in% c("bar", "line")) {
      stop(paste("Please specify type of plot to produce", 
                 "(\"line\", or\n               \"bar\")"))
    }
    data.cols <- data %>% dplyr::select(tidyselect::starts_with("DicerCall_"))
    counts.df <- apply(data.cols, MARGIN = 2, table)
    
    # if a replicate only has unclassified sRNAs (N), then we need to alter
    # beware that any tables which do not have the required columns
    if (base::inherits(counts.df, c("list"))) {
      class_colnames <- colnames(data)[grep("DicerCall_", colnames(data))]
      required_columns <- unique(unlist(data[class_colnames]))
      for (i in seq_len(nrow(counts.df)) ) {
        table_i <- counts.df[[i]]  # current table
        if (length(names(table_i)) < length(required_columns)) {
          # columns missing from the table
          missing_columns <- setdiff(required_columns, names(table_i))
          # add missing columns to table, and assign a value of 0
          table_i[missing_columns] <- 0
          # check order:
          if (!identical(names(table_i), required_columns)) {
            # match order to required order
            table_i <- table_i[match(required_columns, names(table_i))]
          }
          # Update the table in counts.df
          counts.df[[i]] <- table_i 
        }
      }
      # transpose, make dataframe of results. 
      counts.df <- data.frame(t(do.call(rbind, counts.df)))
    } else 
      if (!base::inherits(counts.df, c("list"))) {
        counts.df <- data.frame(counts.df)
      }
    
    
    colnames(counts.df) <- gsub("DicerCall_", "", colnames(counts.df))
    counts.df <- data.table::setDT(counts.df, keep.rownames = "Class")[]
    counts.df <- counts.df[!(counts.df$Class == "N"), ]
    
    
    if (style == "bar") {
      if(!is.null(samples)){
        counts_class <- counts.df %>% select(Class)
        counts.df <- counts.df %>% select(all_of(samples))
        counts.df <- cbind(counts_class,counts.df )
      }
      plist = sapply(names(counts.df)[-grep("Class", names(counts.df))], 
                     function(col) {
                       ggplot2::ggplot(counts.df, 
                                       ggplot2::aes_string(x = "Class",y =col))+ 
                         ggplot2::geom_bar(stat = "identity",fill = colour) + 
                         ggplot2::theme_classic() + 
                         ggplot2::labs(title = paste0("Sample: ", col), x = "sRNA Class", y = "Count")+
                         ggplot2::theme_bw()+
                         ggplot2::theme(legend.position = "right",
                                        plot.title = ggplot2::element_text(face = "bold", size = 18), 
                                        legend.text = ggplot2::element_text(size= 12, margin = ggplot2::margin(5,5,5,5)),
                                        legend.title = ggplot2::element_text(size = 14, face = "bold"),
                                        axis.text.x = ggplot2::element_text(colour = "black", size = 14, face = "bold", margin = ggplot2::margin(t = 10, b = 4)),
                                        axis.text.y = ggplot2::element_text(colour = "black", size = 14,  face = "bold", margin = ggplot2::margin(r = 10)),
                                        panel.grid.major = ggplot2::element_blank(), panel.grid.minor = ggplot2::element_blank(),
                                        panel.background = ggplot2::element_blank(), axis.line = ggplot2::element_line(colour = "black"),
                                        panel.border = ggplot2::element_rect(color = "white", size = 1),
                                        axis.title.y = ggplot2::element_text(margin = ggplot2::margin(r = 15), size = 18, face = "bold"),
                                        axis.title.x = ggplot2::element_text(margin = ggplot2::margin(t = 15), size = 18, face = "bold"),
                                        plot.margin = ggplot2::unit(c(0.1, 0.1,0.1, 0.1),"inches") )
                     }, 
                     simplify = FALSE)
      sn <- names(plist)
      if (facet == TRUE) {
        p <- ggplot2::ggplot(tidyr::gather(counts.df, key, Count, -Class), 
                             ggplot2::aes(Class, Count)) + 
          ggplot2::geom_bar(stat = "identity", fill = colour) + 
          ggplot2::facet_wrap(~key, scales = "free_y", ncol = facet.arrange)+
          ggplot2::labs(x = "sRNA Class", y = "Count")+
          ggplot2::theme_bw()+
          ggplot2::theme(legend.position = "right",
                         legend.text = ggplot2::element_text(size= 12, margin = ggplot2::margin(5,5,5,5)),
                         legend.title = ggplot2::element_text(size = 14, face = "bold"),
                         strip.placement = "outside",
                         strip.background = ggplot2::element_rect(fill = "lightgrey", colour = "white"),
                         strip.text = ggplot2::element_text(size = 12,face="italic" ),
                         axis.text.x = ggplot2::element_text(colour = "black", size = 14, face = "bold", margin = ggplot2::margin(t = 10, b = 4)),
                         axis.text.y = ggplot2::element_text(colour = "black", size = 14,  face = "bold", margin = ggplot2::margin(r = 10)),
                         panel.grid.major = ggplot2::element_blank(), panel.grid.minor = ggplot2::element_blank(),
                         panel.background = ggplot2::element_blank(), axis.line = ggplot2::element_line(colour = "black"),
                         panel.border = ggplot2::element_rect(color = "white", size = 1),
                         axis.title.y = ggplot2::element_text(margin = ggplot2::margin(r = 15), size = 18, face = "bold"),
                         axis.title.x = ggplot2::element_text(margin = ggplot2::margin(t = 15), size = 18, face = "bold"),
                         plot.margin = ggplot2::unit(c(0.1, 0.1,0.1, 0.1),"inches") )
        
        out <- list(plot = p, data = counts.df)
        
      }
      else 
        if (facet == FALSE){
          # save <- list()
          # for (i in 1:length(plist)) {
          #   print(plist[i])
          #   save <- list(save, plist[i])
          # }
          out <- list(plot = plist, data = counts.df)
        }
      return(out)
    }
    if (style == "line") {
      if (together == TRUE) {
        if (is.null(samples)) {
          counts.df_melt <- data.table::melt(counts.df, id.vars = "Class")
          p <- ggplot2::ggplot(counts.df_melt, ggplot2::aes(Class, value, 
                                                            col = variable, 
                                                            group = 1)) + 
            ggplot2::geom_point() + 
            ggplot2::geom_line() + 
            ggplot2::xlab("sRNA Class") + ggplot2::ylab("Count") + 
            ggplot2::labs(color = "Samples")+ 
            ggplot2::guides(fill = ggplot2::guide_legend(override.aes = list(shape = 21, size = 8))) +
            ggplot2::theme_bw()+
            ggplot2::theme(legend.position = "right",
                  legend.text = ggplot2::element_text(size= 12, margin = ggplot2::margin(5,5,5,5)),
                  legend.title = ggplot2::element_text(size = 14, face = "bold"),
                  axis.text.x = ggplot2::element_text(colour = "black", size = 14, face = "bold", margin = ggplot2::margin(t = 10, b = 4)),
                  axis.text.y = ggplot2::element_text(colour = "black", size = 14,  face = "bold", margin = ggplot2::margin(r = 10)),
                  panel.grid.major = ggplot2::element_blank(), panel.grid.minor = ggplot2::element_blank(),
                  panel.background = ggplot2::element_blank(), axis.line = ggplot2::element_line(colour = "black"),
                  panel.border = ggplot2::element_rect(color = "white", size = 1),
                  axis.title.y = ggplot2::element_text(margin = ggplot2::margin(r = 15), size = 18, face = "bold"),
                  axis.title.x = ggplot2::element_text(margin = ggplot2::margin(t = 15), size = 18, face = "bold"),
                  plot.margin = ggplot2::unit(c(0.1, 0.1,0.1, 0.1),"inches") )
          out <- list(plot = p, data = counts.df)
        }
        else 
          if (!is.null(samples)) {
            counts.df <- counts.df %>% select(!all_of(samples))
            counts.df <- data.table::melt(counts.df, id.vars = "Class")
            p <- ggplot2::ggplot(counts.df, ggplot2::aes(Class, 
                                                         value, col = variable, 
                                                         group = 1)) + 
              ggplot2::geom_point(colour = colour) + 
              ggplot2::geom_line(colour = colour) + 
              ggplot2::xlab("sRNA Class") + ggplot2::ylab("Count") + 
              ggplot2::labs(color = "Samples")+ 
              ggplot2::theme_bw()+
              ggplot2::theme(legend.position = "right",
                    legend.text = ggplot2::element_text(size= 12, margin = ggplot2::margin(5,5,5,5)),
                    legend.title = ggplot2::element_text(size = 14, face = "bold"),
                    axis.text.x = ggplot2::element_text(colour = "black", size = 14, face = "bold", margin = ggplot2::margin(t = 10, b = 4)),
                    axis.text.y = ggplot2::element_text(colour = "black", size = 14,  face = "bold", margin = ggplot2::margin(r = 10)),
                    panel.grid.major = ggplot2::element_blank(), panel.grid.minor = ggplot2::element_blank(),
                    panel.background = ggplot2::element_blank(), axis.line = ggplot2::element_line(colour = "black"),
                    panel.border = ggplot2::element_rect(color = "white", size = 1),
                    axis.title.y = ggplot2::element_text(margin = ggplot2::margin(r = 15), size = 18, face = "bold"),
                    axis.title.x = ggplot2::element_text(margin = ggplot2::margin(t = 15), size = 18, face = "bold"),
                    plot.margin = ggplot2::unit(c(0.1, 0.1,0.1, 0.1),"inches") )
            out <- list(plot = p, data = counts.df)
          }
      }
      else 
        if (together == FALSE) {
          if (facet == TRUE) {
            if (is.null(samples)) {
              p <- ggplot2::ggplot(tidyr::gather(counts.df,key, Count, -Class), 
                                   ggplot2::aes(Class, Count, group = 1)) + 
                ggplot2::geom_point(colour = colour) + 
                ggplot2::geom_line(colour = colour) + 
                ggplot2::facet_wrap(~key, scales = "free_y", 
                                    ncol = facet.arrange)+
                ggplot2::xlab("sRNA Class") + ggplot2::ylab("Count") + 
                ggplot2::theme_bw()+
                ggplot2::theme(legend.position = "right",
                      legend.text = ggplot2::element_text(size= 12, margin = ggplot2::margin(5,5,5,5)),
                      legend.title = ggplot2::element_text(size = 14, face = "bold"),
                      strip.placement = "outside",
                      strip.background = ggplot2::element_rect(fill = "lightgrey", colour = "white"),
                      strip.text = ggplot2::element_text(size = 12,face="italic" ),
                      axis.text.x = ggplot2::element_text(colour = "black", size = 14, face = "bold", margin = ggplot2::margin(t = 10, b = 4)),
                      axis.text.y = ggplot2::element_text(colour = "black", size = 14,  face = "bold", margin = ggplot2::margin(r = 10)),
                      panel.grid.major = ggplot2::element_blank(), panel.grid.minor = ggplot2::element_blank(),
                      panel.background = ggplot2::element_blank(), axis.line = ggplot2::element_line(colour = "black"),
                      panel.border = ggplot2::element_rect(color = "white", size = 1),
                      axis.title.y = ggplot2::element_text(margin = ggplot2::margin(r = 15), size = 18, face = "bold"),
                      axis.title.x = ggplot2::element_text(margin = ggplot2::margin(t = 15), size = 18, face = "bold"),
                      plot.margin = ggplot2::unit(c(0.1, 0.1,0.1, 0.1),"inches") )
              
            }
            else if (!is.null(samples)) {
              counts_class <- counts.df %>% select(Class)
              counts.df <- counts.df %>% select(all_of(samples))
              counts.df <- cbind(counts_class,counts.df )
              p <- ggplot2::ggplot(tidyr::gather(counts.df,  key, Count,-Class), 
                                   ggplot2::aes(Class, Count, group = 1)) + 
                ggplot2::geom_point(colour = colour) + 
                ggplot2::geom_line(colour = colour) + 
                ggplot2::theme_classic() + 
                ggplot2::facet_wrap(~key, scales = "free_y", ncol=facet.arrange)+
                ggplot2::theme_bw()+
                ggplot2::theme(legend.position = "right",
                      legend.text = ggplot2::element_text(size= 12, margin = ggplot2::margin(5,5,5,5)),
                      legend.title = ggplot2::element_text(size = 14, face = "bold"),
                      strip.placement = "outside",
                      strip.background = ggplot2::element_rect(fill = "lightgrey", colour = "white"),
                      strip.text = ggplot2::element_text(size = 12,face="italic" ),
                      axis.text.x = ggplot2::element_text(colour = "black", size = 14, face = "bold", margin = ggplot2::margin(t = 10, b = 4)),
                      axis.text.y = ggplot2::element_text(colour = "black", size = 14,  face = "bold", margin = ggplot2::margin(r = 10)),
                      panel.grid.major = ggplot2::element_blank(), panel.grid.minor = ggplot2::element_blank(),
                      panel.background = ggplot2::element_blank(), axis.line = ggplot2::element_line(colour = "black"),
                      panel.border = ggplot2::element_rect(color = "white", size = 1),
                      axis.title.y = ggplot2::element_text(margin = ggplot2::margin(r = 15), size = 18, face = "bold"),
                      axis.title.x = ggplot2::element_text(margin = ggplot2::margin(t = 15), size = 18, face = "bold"),
                      plot.margin = ggplot2::unit(c(0.1, 0.1,0.1, 0.1),"inches") )
            }
            out <- list(plot = p, data = counts.df)
            return(out)
          }
          else if (facet == FALSE) {
            if(!is.null(samples)){
              counts_class <- counts.df %>% select(Class)
              counts.df <- counts.df %>% select(all_of(samples))
              counts.df <- cbind(counts_class,counts.df )
            }
            plist2 = sapply(names(counts.df)[
              -grep("Class", names(counts.df))], function(col) {
                ggplot2::ggplot(counts.df, 
                                ggplot2::aes_string(x ="Class",y =col,group=1))+ 
                  ggplot2::geom_point(colour = colour) + 
                  ggplot2::theme_classic() + 
                  ggplot2::geom_line(colour = colour) + 
                  ggplot2::labs(title = paste0("Sample: ", col), x = "sRNA Class", y = "Count")+
                  ggplot2::theme_bw()+
                  ggplot2::theme(legend.position = "right",
                        plot.title = ggplot2::element_text(face = "bold", size = 18), 
                        legend.text = ggplot2::element_text(size= 12, margin = ggplot2::margin(5,5,5,5)),
                        legend.title = ggplot2::element_text(size = 14, face = "bold"),
                        axis.text.x = ggplot2::element_text(colour = "black", size = 14, face = "bold", margin = ggplot2::margin(t = 10, b = 4)),
                        axis.text.y = ggplot2::element_text(colour = "black", size = 14,  face = "bold", margin = ggplot2::margin(r = 10)),
                        panel.grid.major = ggplot2::element_blank(), panel.grid.minor = ggplot2::element_blank(),
                        panel.background = ggplot2::element_blank(), axis.line = ggplot2::element_line(colour = "black"),
                        panel.border = ggplot2::element_rect(color = "white", size = 1),
                        axis.title.y = ggplot2::element_text(margin = ggplot2::margin(r = 15), size = 18, face = "bold"),
                        axis.title.x = ggplot2::element_text(margin = ggplot2::margin(t = 15), size = 18, face = "bold"),
                        plot.margin = ggplot2::unit(c(0.1, 0.1,0.1, 0.1),"inches") )}, 
              simplify = FALSE)
            sn <- names(plist2)
            p <- plist2
            out <- list(plot = p, data = counts.df)
            
            
            #for (J in 1:length(plist2)) {
            #print(plist2[J])
            #}
          }
        }
      return(out) 
    }
  }
}
