#' Subset data to select a specific sRNA population based on dicercall size 
#'
#' @description Creates a dataframe containing the desired sRNA class(s) based
#' on the consensus dicercall determination.
#'
#' @details
#' See [mobileRNA::RNAdicercall()] for information on defining the sRNA 
#' dicercall class for each cluster. The function allows the choice to filtered 
#' the data by statistical statisticalnificance based on differential expression 
#' analysis, see [mobileRNA::RNAdifferentialAnalysis()]. Set 
#' \code{statistical=TRUE} to filtered by statisticalnificance (p-adjusted). 
#' It is important to consider the point in your analysis you subset the data 
#' or/and undertake differential analysis to achieve statistical values. 
#' Subsetting the dataset into groups based on the sRNA class will
#' create a smaller set of data for each to draw statistical differences.
#' Depending on the size of your data, and analysis aims this should be taken
#' into consideration.
#'
#' @param data data.frame; generated by [mobileRNA::RNAimport()], containing 
#' the additional information generated by [mobileRNA::RNAdicercall()] which 
#' defines the consensus sRNA class for each sRNA dicer-derived clusters
#'
#' @param class numeric; sRNA dicercall class(es) to select. Based on size in 
#' nucleotides. 
#' 
#' @param statistical logical; filter and select statistical significant sRNA. 
#' If \code{statistical=TRUE}, sRNA clusters are selected based on 
#' p-adjusted alpha threshold.
#' 
#' @param alpha numeric; user defined numeric value to represent the adjusted 
#' p-value threshold to define statistic significance. Defaults setting 
#' `alpha=0.05`. 
#'
#' @return A dataframe containing only sRNA clusters defined with a specific 
#' sRNA dicer-derived consensus size.
#' 
#' @examples
#' data("sRNA_data_dicercall")
#'
#' # Subset data for  24-nt sRNAs
#' sRNA_24 <- RNAsubset(sRNA_data_dicercall, class = 24)
#'
#'
#'# Subset data for 21/22-nt sRNAs
#'sRNA_2122 <- RNAsubset(sRNA_data_dicercall, class = c(21, 22))
#'
#' @export
#' @importFrom dplyr "%>%"
#' @importFrom dplyr "filter"

RNAsubset <- function(data, class,  statistical=FALSE, alpha = 0.05){
  if (!base::inherits(data, c("matrix", "data.frame", "DataFrame"))) {
    stop("data must be an object of class matrix, data.frame, DataFrame")
  }
  if (base::missing(class) || !base::inherits(class, "numeric")) {
    stop("Please specify a numeric vector stating the class of sRNAs to select")
  }
    x <- data %>% dplyr::filter(DicerConsensus %in% class)
    if(statistical){
      x<- x %>%
        dplyr::filter(padj < alpha)
    }
    return(x)
  }

